# Generated by Django 3.2.12 on 2022-03-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(unique=True)),
                ('token', models.UUIDField(unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account_id', models.UUIDField()),
                ('destination_account_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destination_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_bank_transfer_request', to='bank_agent.bank')),
                ('source_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bank_transfer_request', to='bank_agent.bank')),
            ],
        ),
    ]
