# Generated by Django 3.2.12 on 2022-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
