# Generated by Django 3.2.12 on 2022-03-22 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_agent', '0003_transferrequest_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
