# Generated by Django 3.2.12 on 2022-03-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_agent', '0004_alter_transferrequest_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='service_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
